apiVersion: apps/v1
kind: Deployment
metadata:
  name: dictionary-deployment
  labels:
    app: dictionary
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dictionary
  template:
    metadata:
      labels:
        app: dictionary
    spec:
      containers:
      - name: dictionary
        image: ghcr.io/saranuu/nextjs_dictionary_app:latest
        ports:
        - containerPort: 3000

